#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034,SC2154

START=99
USE_PROCD=1

script=$(readlink "$initscript")
NAME="$(basename ${script:-$initscript})"
config_load "$NAME"

start_service() {
    echo "Start podkop"

    config_get enable_badwan_interface_monitoring "settings" "enable_badwan_interface_monitoring"
    config_get badwan_monitored_interfaces "settings" "badwan_monitored_interfaces"

    procd_open_instance
    procd_set_param command /usr/bin/podkop start
    [ "$enable_badwan_interface_monitoring" = "1" ] && [ -n "$badwan_monitored_interfaces" ] &&
        procd_set_param netdev "$badwan_monitored_interfaces"
    procd_set_param stdout 1
    procd_set_param stderr 1

    # Watchdog 
    (
        MAX_RESTARTS=3
        COUNTER_FILE="/tmp/podkop_watchdog_restarts"
        SLEEP_BEFORE_CHECK=10

        sleep $SLEEP_BEFORE_CHECK
        logger -t podkop_watchdog "Starting podkop watchdog ..."

        restarts=0
        [ -f "$COUNTER_FILE" ] && restarts=$(cat "$COUNTER_FILE")

        if [ "$restarts" -ge "$MAX_RESTARTS" ]; then
            logger -t podkop_watchdog "Max restarts ($MAX_RESTARTS) reached. Giving up."
            rm -f "$COUNTER_FILE"
            exit 1
        fi

        health=$(/usr/bin/podkop global_check)
        if ! echo "$health" | grep -qiE "failed|Router DNS is NOT routed through sing-box"; then
            rm -f "$COUNTER_FILE"
            logger -t podkop_watchdog "Health check PASSED. Watchdog finished."
            exit 0
        else
            failed=$(echo "$health" | grep -iE "failed|Router DNS is NOT routed through sing-box")
        fi

        restarts=$((restarts + 1))
        echo "$restarts" > "$COUNTER_FILE"

        if [ "$restarts" -ge "$MAX_RESTARTS" ]; then
            logger -t podkop_watchdog "Health check FAILED after $MAX_RESTARTS restarts. Giving up."
            rm -f "$COUNTER_FILE"
            exit 1
        fi

        logger -t podkop_watchdog "Health check FAILED ($failed) (restart $restarts of $MAX_RESTARTS). Restarting podkop..."
        /etc/init.d/podkop restart
        exit 0
    ) &

    procd_close_instance
}

stop_service() {
    /usr/bin/podkop stop
}

reload_service() {
    /usr/bin/podkop reload > /dev/null 2>&1
}

service_triggers() {
    echo "service_triggers start"

    config_get enable_badwan_interface_monitoring "settings" "enable_badwan_interface_monitoring"
    config_get badwan_monitored_interfaces "settings" "badwan_monitored_interfaces"
    config_get badwan_reload_delay "settings" "badwan_reload_delay" "2000"

    PROCD_RELOAD_DELAY=$badwan_reload_delay

    procd_open_trigger
    procd_add_config_trigger "config.change" "$NAME" "$initscript" restart 'on_config_change'

    if [ "$enable_badwan_interface_monitoring" = "1" ]; then
        for iface in $badwan_monitored_interfaces; do
            procd_add_interface_trigger "interface.*.up" "$iface" /etc/init.d/podkop restart
        done
    fi
    procd_close_trigger
}